ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS codigo_cliente text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS tipo_perfil text default 'comum';
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS nome_razao_social text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS fantasia text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS cpf_cnpj text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS inscricao_estadual text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS inscricao_municipal text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS rg text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS data_nascimento text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS telefone1 text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS telefone2 text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS telefone3 text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS conjuge_contato text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS socio text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS socio_cpf text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS nome_pai text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS nome_mae text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS empreiteiro_id text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS empreiteiro_nome text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS obras jsonb default '[]'::jsonb;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS endereco_entrega_rua text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS endereco_entrega_numero text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS endereco_entrega_complemento text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS endereco_entrega_bairro text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS endereco_entrega_cidade text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS endereco_entrega_uf text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS endereco_entrega_cep text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS endereco_cobranca_rua text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS endereco_cobranca_numero text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS endereco_cobranca_complemento text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS endereco_cobranca_bairro text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS endereco_cobranca_cidade text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS endereco_cobranca_uf text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS endereco_cobranca_cep text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS pessoas_liberadas jsonb default '[]'::jsonb;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS etiquetas jsonb default '[]'::jsonb;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS data_validade_cadastro text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS bloqueado boolean default false;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS pendencia_financeira boolean default false;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS status_serasa text default 'limpo';
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS observacoes text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS motivo_bloqueio text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS financeiro_bloqueio_automatico boolean default false;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS financeiro_limite_bloqueio numeric default 0;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS financeiro_dias_carencia numeric default 0;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS financeiro_faturamento_automatico boolean default false;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS financeiro_intervalo_faturamento numeric default 30;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS financeiro_observacoes text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS foto_url text;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS numero text;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS client_id uuid references public.clients(id) on delete set null;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS client_nome text;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS data_inicio text;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS sem_prazo boolean;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS prazo_tipo text;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS prazo_valor numeric;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS data_prevista_termino text;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS solicitante_nome text;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS solicitante_tipo text;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS obra_nome text;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS obra_endereco text;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS itens jsonb default '[]'::jsonb;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS frete text;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS sinal text;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS valor_total numeric;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS valor_pago text;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS saldo_pagar numeric;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS status_financeiro text;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS endereco_entrega text;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS observacoes text;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS tipo_entrega text;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS codigo_contrato text;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS data_fim date;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS data_recolha date;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS motorista_entrega text;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS veiculo_entrega text;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS assinatura_data timestamp with time zone;
ALTER TABLE public.contracts ADD COLUMN IF NOT EXISTS fotos jsonb default '[]'::jsonb;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS nome text;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS marca text;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS modelo text;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS tipos jsonb default '["equipamento"]'::jsonb;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS voltagem text;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS codigo text;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS foto_url text;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS link_externo text;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS quantidade_total numeric;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS quantidade_disponivel numeric;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS quantidade_manutencao numeric;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS status_item text;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS valor_diario numeric;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS valor_mensal numeric;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS valor_indenizacao numeric;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS descricao text;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS ativo boolean default true;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS aplica_valor_minimo boolean;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS dias_minimos_proprio numeric;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS aplica_desconto_automatico boolean;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS controle_individual boolean;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS numeracoes jsonb default '[]'::jsonb;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS categoria text;
ALTER TABLE public.equipment ADD COLUMN IF NOT EXISTS valor_locacao numeric;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS nome text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS codigo text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS codigo_barras text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS categoria text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS marca text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS modelo text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS custo numeric;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS margem numeric;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS valor_venda numeric;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS estoque_atual numeric;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS estoque_minimo numeric;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS unidade text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS descricao text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS ativo boolean default true;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS preco numeric;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS estoque integer;
ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS nome text;
ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS telefone text;
ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS cnh text;
ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS veiculo text;
ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS placa text;
ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS cor text;
ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS status text default 'ativo';
ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS observacoes text;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS titulo text;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS descricao text;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS imagem_url text;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS categoria text;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS prioridade text;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS data text;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS data_inicio text;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS data_fim text;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS hora_publicacao text;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS ativo boolean;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS destaque boolean;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS fixado boolean;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS exibir_portal boolean;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS setor_destino text;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS responsavel text;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS anexos jsonb default '[]'::jsonb;
ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS placa text;
ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS modelo text;
ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS marca text;
ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS ano text;
ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS km_atual text;
ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS status text default 'ativo';
ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS chassi text;
ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS renavam text;
ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS tipo text;
ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS combustivel text;
ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS capacidade_carga text;
ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS observacoes text;
ALTER TABLE public.vehicles ADD COLUMN IF NOT EXISTS foto_url text;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS client_id uuid references public.clients(id) on delete set null;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS client_nome text;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS data_venda text;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS itens jsonb default '[]'::jsonb;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS valor_total numeric;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS valor_desconto numeric;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS valor_final numeric;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS forma_pagamento text;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS observacoes text;
ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS client_id uuid references public.clients(id) on delete set null;
ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS client_nome text;
ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS os_origem_id uuid references public.service_orders(id);
ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS tipo text;
ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS data_agendada text;
ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS data_conclusao text;
ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS motorista_entrega text;
ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS veiculo_entrega text;
ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS fotos jsonb default '[]'::jsonb;
ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS itens jsonb default '[]'::jsonb;
ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS status_pagamento text;
ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS valor_total numeric;
ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS observacoes text;